//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightSchedule
    {
        public int Id { get; set; }
        public string SourceCity { get; set; }
        public string DestinationCity { get; set; }
        public System.TimeSpan TakeOffTime { get; set; }
        public System.TimeSpan ArrivalTime { get; set; }
        public int Price { get; set; }
        public string FlightDay { get; set; }
        public int TotalSeats { get; set; }
        public Nullable<int> SeatsBooked { get; set; }
        public Nullable<int> AvailableSeats { get; set; }
    }
}
