//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegister
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserRegister()
        {
            this.BookingSchedules = new HashSet<BookingSchedule>();
        }
    
        public int UserID { get; set; }
        public string Title { get; set; }
        public string Surname { get; set; }
        public string OtherName { get; set; }
        public System.DateTime DOB { get; set; }
        public string CountryOfResidence { get; set; }
        public string Nationality { get; set; }
        public string Email { get; set; }
        public long PhoneNo { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingSchedule> BookingSchedules { get; set; }
    }
}
